/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminShippingZonesRouteImport } from './routes/admin.shipping-zones'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminFlashSalesRouteImport } from './routes/admin.flash-sales'
import { Route as AdminAbandonedCartsRouteImport } from './routes/admin.abandoned-carts'
import { Route as AdminWishlistAnalyticsRouteImport } from './routes/admin.wishlist-analytics'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminGiftCardsRouteImport } from './routes/admin.gift-cards'
import { Route as AdminSalesAnalyticsRouteImport } from './routes/admin.sales-analytics'
import { Route as AdminProductPerformanceRouteImport } from './routes/admin.product-performance'
import { Route as AdminConversionTrackingRouteImport } from './routes/admin.conversion-tracking'
import { Route as AdminSearchAnalyticsRouteImport } from './routes/admin.search-analytics'
import { Route as AdminAutomationRulesRouteImport } from './routes/admin.automation-rules'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminSmsTemplatesRouteImport } from './routes/admin.sms-templates'
import { Route as AdminPushNotificationsRouteImport } from './routes/admin.push-notifications'
import { Route as AdminApiManagementRouteImport } from './routes/admin.api-management'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminSupportTicketsRouteImport } from './routes/admin.support-tickets'
import { Route as AdminLiveChatRouteImport } from './routes/admin.live-chat'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminLoginSessionsRouteImport } from './routes/admin.login-sessions'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminFraudDetectionRouteImport } from './routes/admin.fraud-detection'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUsersBannedRouteImport } from './routes/admin.users.banned'
import { Route as AdminUsersRolesRouteImport } from './routes/admin.users.roles'
import { Route as AdminVendorsPendingRouteImport } from './routes/admin.vendors.pending'
import { Route as AdminVendorsPerformanceRouteImport } from './routes/admin.vendors.performance'
import { Route as AdminProductsAddRouteImport } from './routes/admin.products.add'
import { Route as AdminProductsCategoriesRouteImport } from './routes/admin.products.categories'
import { Route as AdminProductsSubcategoriesRouteImport } from './routes/admin.products.subcategories'
import { Route as AdminProductsBrandsRouteImport } from './routes/admin.products.brands'
import { Route as AdminProductsAttributesRouteImport } from './routes/admin.products.attributes'
import { Route as AdminProductsInventoryRouteImport } from './routes/admin.products.inventory'
import { Route as AdminOrdersPendingRouteImport } from './routes/admin.orders.pending'
import { Route as AdminOrdersProcessingRouteImport } from './routes/admin.orders.processing'
import { Route as AdminOrdersShippedRouteImport } from './routes/admin.orders.shipped'
import { Route as AdminOrdersDeliveredRouteImport } from './routes/admin.orders.delivered'
import { Route as AdminOrdersCancelledRouteImport } from './routes/admin.orders.cancelled'
import { Route as AdminOrdersReturnsRouteImport } from './routes/admin.orders.returns'
import { Route as AdminShippingChargesRouteImport } from './routes/admin.shipping.charges'
import { Route as AdminShippingCourierRouteImport } from './routes/admin.shipping.courier'
import { Route as AdminMarketingPromotionsRouteImport } from './routes/admin.marketing.promotions'
import { Route as AdminReviewsModerationRouteImport } from './routes/admin.reviews.moderation'
import { Route as AdminSupportComplaintsRouteImport } from './routes/admin.support.complaints'
import { Route as AdminSupportHelpCenterRouteImport } from './routes/admin.support.help-center'
import { Route as AdminSecurityIpRouteImport } from './routes/admin.security.ip'
import { Route as AdminSettingsCurrencyRouteImport } from './routes/admin.settings.currency'
import { Route as AdminSettingsEmailRouteImport } from './routes/admin.settings.email'
import { Route as AdminSettingsOtpRouteImport } from './routes/admin.settings.otp'
import { Route as AdminLogsErrorsRouteImport } from './routes/admin.logs.errors'
import { Route as AdminBackupRestoreRouteImport } from './routes/admin.backup.restore'
import { Route as AdminApiIntegrationsRouteImport } from './routes/admin.api.integrations'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountTransactionsRouteImport } from './routes/account.transactions'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountRewardsRouteImport } from './routes/account.rewards'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountRefundsRouteImport } from './routes/account.refunds'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPayoutsRouteImport } from './routes/account.payouts'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountMarketingRouteImport } from './routes/account.marketing'
import { Route as AccountDeliveryRouteImport } from './routes/account.delivery'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountRefundsIdRouteImport } from './routes/account.refunds.$id'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({ id: '/transactions', path: '/transactions', getParentRoute: () => AdminRoute } as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({ id: '/payment-methods', path: '/payment-methods', getParentRoute: () => AdminRoute } as any)
const AdminShippingZonesRoute = AdminShippingZonesRouteImport.update({ id: '/shipping-zones', path: '/shipping-zones', getParentRoute: () => AdminRoute } as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({ id: '/coupons', path: '/coupons', getParentRoute: () => AdminRoute } as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({ id: '/campaigns', path: '/campaigns', getParentRoute: () => AdminRoute } as any)
const AdminBannersRoute = AdminBannersRouteImport.update({ id: '/banners', path: '/banners', getParentRoute: () => AdminRoute } as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({ id: '/reviews', path: '/reviews', getParentRoute: () => AdminRoute } as any)
const AdminReportsRoute = AdminReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AdminRoute } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => AdminRoute } as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AdminRoute } as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({ id: '/payouts', path: '/payouts', getParentRoute: () => AdminRoute } as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({ id: '/commissions', path: '/commissions', getParentRoute: () => AdminRoute } as any)
const AdminFlashSalesRoute = AdminFlashSalesRouteImport.update({ id: '/flash-sales', path: '/flash-sales', getParentRoute: () => AdminRoute } as any)
const AdminAbandonedCartsRoute = AdminAbandonedCartsRouteImport.update({ id: '/abandoned-carts', path: '/abandoned-carts', getParentRoute: () => AdminRoute } as any)
const AdminWishlistAnalyticsRoute = AdminWishlistAnalyticsRouteImport.update({ id: '/wishlist-analytics', path: '/wishlist-analytics', getParentRoute: () => AdminRoute } as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({ id: '/segments', path: '/segments', getParentRoute: () => AdminRoute } as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({ id: '/loyalty', path: '/loyalty', getParentRoute: () => AdminRoute } as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({ id: '/subscriptions', path: '/subscriptions', getParentRoute: () => AdminRoute } as any)
const AdminGiftCardsRoute = AdminGiftCardsRouteImport.update({ id: '/gift-cards', path: '/gift-cards', getParentRoute: () => AdminRoute } as any)
const AdminSalesAnalyticsRoute = AdminSalesAnalyticsRouteImport.update({ id: '/sales-analytics', path: '/sales-analytics', getParentRoute: () => AdminRoute } as any)
const AdminProductPerformanceRoute = AdminProductPerformanceRouteImport.update({ id: '/product-performance', path: '/product-performance', getParentRoute: () => AdminRoute } as any)
const AdminConversionTrackingRoute = AdminConversionTrackingRouteImport.update({ id: '/conversion-tracking', path: '/conversion-tracking', getParentRoute: () => AdminRoute } as any)
const AdminSearchAnalyticsRoute = AdminSearchAnalyticsRouteImport.update({ id: '/search-analytics', path: '/search-analytics', getParentRoute: () => AdminRoute } as any)
const AdminAutomationRulesRoute = AdminAutomationRulesRouteImport.update({ id: '/automation-rules', path: '/automation-rules', getParentRoute: () => AdminRoute } as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({ id: '/email-templates', path: '/email-templates', getParentRoute: () => AdminRoute } as any)
const AdminSmsTemplatesRoute = AdminSmsTemplatesRouteImport.update({ id: '/sms-templates', path: '/sms-templates', getParentRoute: () => AdminRoute } as any)
const AdminPushNotificationsRoute = AdminPushNotificationsRouteImport.update({ id: '/push-notifications', path: '/push-notifications', getParentRoute: () => AdminRoute } as any)
const AdminApiManagementRoute = AdminApiManagementRouteImport.update({ id: '/api-management', path: '/api-management', getParentRoute: () => AdminRoute } as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({ id: '/webhooks', path: '/webhooks', getParentRoute: () => AdminRoute } as any)
const AdminSupportTicketsRoute = AdminSupportTicketsRouteImport.update({ id: '/support-tickets', path: '/support-tickets', getParentRoute: () => AdminRoute } as any)
const AdminLiveChatRoute = AdminLiveChatRouteImport.update({ id: '/live-chat', path: '/live-chat', getParentRoute: () => AdminRoute } as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({ id: '/feedback', path: '/feedback', getParentRoute: () => AdminRoute } as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({ id: '/disputes', path: '/disputes', getParentRoute: () => AdminRoute } as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({ id: '/refunds', path: '/refunds', getParentRoute: () => AdminRoute } as any)
const AdminPagesRoute = AdminPagesRouteImport.update({ id: '/pages', path: '/pages', getParentRoute: () => AdminRoute } as any)
const AdminBlogRoute = AdminBlogRouteImport.update({ id: '/blog', path: '/blog', getParentRoute: () => AdminRoute } as any)
const AdminMediaRoute = AdminMediaRouteImport.update({ id: '/media', path: '/media', getParentRoute: () => AdminRoute } as any)
const AdminSeoRoute = AdminSeoRouteImport.update({ id: '/seo', path: '/seo', getParentRoute: () => AdminRoute } as any)
const AdminRolesRoute = AdminRolesRouteImport.update({ id: '/roles', path: '/roles', getParentRoute: () => AdminRoute } as any)
const AdminLoginSessionsRoute = AdminLoginSessionsRouteImport.update({ id: '/login-sessions', path: '/login-sessions', getParentRoute: () => AdminRoute } as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({ id: '/security', path: '/security', getParentRoute: () => AdminRoute } as any)
const AdminFraudDetectionRoute = AdminFraudDetectionRouteImport.update({ id: '/fraud-detection', path: '/fraud-detection', getParentRoute: () => AdminRoute } as any)
const AdminBackupRoute = AdminBackupRouteImport.update({ id: '/backup', path: '/backup', getParentRoute: () => AdminRoute } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({ id: '/users', path: '/users', getParentRoute: () => AdminRoute } as any)
const AdminUsersBannedRoute = AdminUsersBannedRouteImport.update({ id: '/users/banned', path: '/users/banned', getParentRoute: () => AdminRoute } as any)
const AdminUsersRolesRoute = AdminUsersRolesRouteImport.update({ id: '/users/roles', path: '/users/roles', getParentRoute: () => AdminRoute } as any)
const AdminVendorsPendingRoute = AdminVendorsPendingRouteImport.update({ id: '/vendors/pending', path: '/vendors/pending', getParentRoute: () => AdminRoute } as any)
const AdminVendorsPerformanceRoute = AdminVendorsPerformanceRouteImport.update({ id: '/vendors/performance', path: '/vendors/performance', getParentRoute: () => AdminRoute } as any)
const AdminProductsAddRoute = AdminProductsAddRouteImport.update({ id: '/products/add', path: '/products/add', getParentRoute: () => AdminRoute } as any)
const AdminProductsCategoriesRoute = AdminProductsCategoriesRouteImport.update({ id: '/products/categories', path: '/products/categories', getParentRoute: () => AdminRoute } as any)
const AdminProductsSubcategoriesRoute = AdminProductsSubcategoriesRouteImport.update({ id: '/products/subcategories', path: '/products/subcategories', getParentRoute: () => AdminRoute } as any)
const AdminProductsBrandsRoute = AdminProductsBrandsRouteImport.update({ id: '/products/brands', path: '/products/brands', getParentRoute: () => AdminRoute } as any)
const AdminProductsAttributesRoute = AdminProductsAttributesRouteImport.update({ id: '/products/attributes', path: '/products/attributes', getParentRoute: () => AdminRoute } as any)
const AdminProductsInventoryRoute = AdminProductsInventoryRouteImport.update({ id: '/products/inventory', path: '/products/inventory', getParentRoute: () => AdminRoute } as any)
const AdminOrdersPendingRoute = AdminOrdersPendingRouteImport.update({ id: '/orders/pending', path: '/orders/pending', getParentRoute: () => AdminRoute } as any)
const AdminOrdersProcessingRoute = AdminOrdersProcessingRouteImport.update({ id: '/orders/processing', path: '/orders/processing', getParentRoute: () => AdminRoute } as any)
const AdminOrdersShippedRoute = AdminOrdersShippedRouteImport.update({ id: '/orders/shipped', path: '/orders/shipped', getParentRoute: () => AdminRoute } as any)
const AdminOrdersDeliveredRoute = AdminOrdersDeliveredRouteImport.update({ id: '/orders/delivered', path: '/orders/delivered', getParentRoute: () => AdminRoute } as any)
const AdminOrdersCancelledRoute = AdminOrdersCancelledRouteImport.update({ id: '/orders/cancelled', path: '/orders/cancelled', getParentRoute: () => AdminRoute } as any)
const AdminOrdersReturnsRoute = AdminOrdersReturnsRouteImport.update({ id: '/orders/returns', path: '/orders/returns', getParentRoute: () => AdminRoute } as any)
const AdminShippingChargesRoute = AdminShippingChargesRouteImport.update({ id: '/shipping/charges', path: '/shipping/charges', getParentRoute: () => AdminRoute } as any)
const AdminShippingCourierRoute = AdminShippingCourierRouteImport.update({ id: '/shipping/courier', path: '/shipping/courier', getParentRoute: () => AdminRoute } as any)
const AdminMarketingPromotionsRoute = AdminMarketingPromotionsRouteImport.update({ id: '/marketing/promotions', path: '/marketing/promotions', getParentRoute: () => AdminRoute } as any)
const AdminReviewsModerationRoute = AdminReviewsModerationRouteImport.update({ id: '/reviews/moderation', path: '/reviews/moderation', getParentRoute: () => AdminRoute } as any)
const AdminSupportComplaintsRoute = AdminSupportComplaintsRouteImport.update({ id: '/support/complaints', path: '/support/complaints', getParentRoute: () => AdminRoute } as any)
const AdminSupportHelpCenterRoute = AdminSupportHelpCenterRouteImport.update({ id: '/support/help-center', path: '/support/help-center', getParentRoute: () => AdminRoute } as any)
const AdminSecurityIpRoute = AdminSecurityIpRouteImport.update({ id: '/security/ip', path: '/security/ip', getParentRoute: () => AdminRoute } as any)
const AdminSettingsCurrencyRoute = AdminSettingsCurrencyRouteImport.update({ id: '/settings/currency', path: '/settings/currency', getParentRoute: () => AdminRoute } as any)
const AdminSettingsEmailRoute = AdminSettingsEmailRouteImport.update({ id: '/settings/email', path: '/settings/email', getParentRoute: () => AdminRoute } as any)
const AdminSettingsOtpRoute = AdminSettingsOtpRouteImport.update({ id: '/settings/otp', path: '/settings/otp', getParentRoute: () => AdminRoute } as any)
const AdminLogsErrorsRoute = AdminLogsErrorsRouteImport.update({ id: '/logs/errors', path: '/logs/errors', getParentRoute: () => AdminRoute } as any)
const AdminBackupRestoreRoute = AdminBackupRestoreRouteImport.update({ id: '/backup/restore', path: '/backup/restore', getParentRoute: () => AdminRoute } as any)
const AdminApiIntegrationsRoute = AdminApiIntegrationsRouteImport.update({ id: '/api/integrations', path: '/api/integrations', getParentRoute: () => AdminRoute } as any)

const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTransactionsRoute = AccountTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRefundsRoute = AccountRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPayoutsRoute = AccountPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMarketingRoute = AccountMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDeliveryRoute = AccountDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountRefundsIdRoute = AccountRefundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountRefundsRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/shipping-zones': typeof AdminShippingZonesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/wishlist-analytics': typeof AdminWishlistAnalyticsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/sales-analytics': typeof AdminSalesAnalyticsRoute
  '/admin/product-performance': typeof AdminProductPerformanceRoute
  '/admin/conversion-tracking': typeof AdminConversionTrackingRoute
  '/admin/search-analytics': typeof AdminSearchAnalyticsRoute
  '/admin/automation-rules': typeof AdminAutomationRulesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/sms-templates': typeof AdminSmsTemplatesRoute
  '/admin/push-notifications': typeof AdminPushNotificationsRoute
  '/admin/api-management': typeof AdminApiManagementRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/login-sessions': typeof AdminLoginSessionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/fraud-detection': typeof AdminFraudDetectionRoute
  '/admin/backup': typeof AdminBackupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/shipping-zones': typeof AdminShippingZonesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/wishlist-analytics': typeof AdminWishlistAnalyticsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/sales-analytics': typeof AdminSalesAnalyticsRoute
  '/admin/product-performance': typeof AdminProductPerformanceRoute
  '/admin/conversion-tracking': typeof AdminConversionTrackingRoute
  '/admin/search-analytics': typeof AdminSearchAnalyticsRoute
  '/admin/automation-rules': typeof AdminAutomationRulesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/sms-templates': typeof AdminSmsTemplatesRoute
  '/admin/push-notifications': typeof AdminPushNotificationsRoute
  '/admin/api-management': typeof AdminApiManagementRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/login-sessions': typeof AdminLoginSessionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/fraud-detection': typeof AdminFraudDetectionRoute
  '/admin/backup': typeof AdminBackupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/shipping-zones': typeof AdminShippingZonesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/wishlist-analytics': typeof AdminWishlistAnalyticsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/gift-cards': typeof AdminGiftCardsRoute
  '/admin/sales-analytics': typeof AdminSalesAnalyticsRoute
  '/admin/product-performance': typeof AdminProductPerformanceRoute
  '/admin/conversion-tracking': typeof AdminConversionTrackingRoute
  '/admin/search-analytics': typeof AdminSearchAnalyticsRoute
  '/admin/automation-rules': typeof AdminAutomationRulesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/sms-templates': typeof AdminSmsTemplatesRoute
  '/admin/push-notifications': typeof AdminPushNotificationsRoute
  '/admin/api-management': typeof AdminApiManagementRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/login-sessions': typeof AdminLoginSessionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/fraud-detection': typeof AdminFraudDetectionRoute
  '/admin/backup': typeof AdminBackupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/activity-logs'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/payment-methods'
    | '/admin/shipping-zones'
    | '/admin/coupons'
    | '/admin/campaigns'
    | '/admin/banners'
    | '/admin/reviews'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/payouts'
    | '/admin/commissions'
    | '/admin/flash-sales'
    | '/admin/abandoned-carts'
    | '/admin/wishlist-analytics'
    | '/admin/segments'
    | '/admin/loyalty'
    | '/admin/subscriptions'
    | '/admin/gift-cards'
    | '/admin/sales-analytics'
    | '/admin/product-performance'
    | '/admin/conversion-tracking'
    | '/admin/search-analytics'
    | '/admin/automation-rules'
    | '/admin/email-templates'
    | '/admin/sms-templates'
    | '/admin/push-notifications'
    | '/admin/api-management'
    | '/admin/webhooks'
    | '/admin/support-tickets'
    | '/admin/live-chat'
    | '/admin/feedback'
    | '/admin/disputes'
    | '/admin/refunds'
    | '/admin/pages'
    | '/admin/blog'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/roles'
    | '/admin/login-sessions'
    | '/admin/security'
    | '/admin/fraud-detection'
    | '/admin/backup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/product/$id'
    | '/shop/$category'
    | '/account/'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/activity-logs'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/payment-methods'
    | '/admin/shipping-zones'
    | '/admin/coupons'
    | '/admin/campaigns'
    | '/admin/banners'
    | '/admin/reviews'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/payouts'
    | '/admin/commissions'
    | '/admin/flash-sales'
    | '/admin/abandoned-carts'
    | '/admin/wishlist-analytics'
    | '/admin/segments'
    | '/admin/loyalty'
    | '/admin/subscriptions'
    | '/admin/gift-cards'
    | '/admin/sales-analytics'
    | '/admin/product-performance'
    | '/admin/conversion-tracking'
    | '/admin/search-analytics'
    | '/admin/automation-rules'
    | '/admin/email-templates'
    | '/admin/sms-templates'
    | '/admin/push-notifications'
    | '/admin/api-management'
    | '/admin/webhooks'
    | '/admin/support-tickets'
    | '/admin/live-chat'
    | '/admin/feedback'
    | '/admin/disputes'
    | '/admin/refunds'
    | '/admin/pages'
    | '/admin/blog'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/roles'
    | '/admin/login-sessions'
    | '/admin/security'
    | '/admin/fraud-detection'
    | '/admin/backup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/product/$id'
    | '/shop/$category'
    | '/account'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/activity-logs'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/payment-methods'
    | '/admin/shipping-zones'
    | '/admin/coupons'
    | '/admin/campaigns'
    | '/admin/banners'
    | '/admin/reviews'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/payouts'
    | '/admin/commissions'
    | '/admin/flash-sales'
    | '/admin/abandoned-carts'
    | '/admin/wishlist-analytics'
    | '/admin/segments'
    | '/admin/loyalty'
    | '/admin/subscriptions'
    | '/admin/gift-cards'
    | '/admin/sales-analytics'
    | '/admin/product-performance'
    | '/admin/conversion-tracking'
    | '/admin/search-analytics'
    | '/admin/automation-rules'
    | '/admin/email-templates'
    | '/admin/sms-templates'
    | '/admin/push-notifications'
    | '/admin/api-management'
    | '/admin/webhooks'
    | '/admin/support-tickets'
    | '/admin/live-chat'
    | '/admin/feedback'
    | '/admin/disputes'
    | '/admin/refunds'
    | '/admin/pages'
    | '/admin/blog'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/roles'
    | '/admin/login-sessions'
    | '/admin/security'
    | '/admin/fraud-detection'
    | '/admin/backup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/product/$id'
    | '/shop/$category'
    | '/account/'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SellerRoute: typeof SellerRoute
  ShopRoute: typeof ShopRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': { id: '/admin/transactions'; path: '/transactions'; fullPath: '/admin/transactions'; preLoaderRoute: typeof AdminTransactionsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/payment-methods': { id: '/admin/payment-methods'; path: '/payment-methods'; fullPath: '/admin/payment-methods'; preLoaderRoute: typeof AdminPaymentMethodsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/shipping-zones': { id: '/admin/shipping-zones'; path: '/shipping-zones'; fullPath: '/admin/shipping-zones'; preLoaderRoute: typeof AdminShippingZonesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/coupons': { id: '/admin/coupons'; path: '/coupons'; fullPath: '/admin/coupons'; preLoaderRoute: typeof AdminCouponsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/campaigns': { id: '/admin/campaigns'; path: '/campaigns'; fullPath: '/admin/campaigns'; preLoaderRoute: typeof AdminCampaignsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/banners': { id: '/admin/banners'; path: '/banners'; fullPath: '/admin/banners'; preLoaderRoute: typeof AdminBannersRouteImport; parentRoute: typeof AdminRoute }
    '/admin/reviews': { id: '/admin/reviews'; path: '/reviews'; fullPath: '/admin/reviews'; preLoaderRoute: typeof AdminReviewsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/reports': { id: '/admin/reports'; path: '/reports'; fullPath: '/admin/reports'; preLoaderRoute: typeof AdminReportsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/notifications': { id: '/admin/notifications'; path: '/notifications'; fullPath: '/admin/notifications'; preLoaderRoute: typeof AdminNotificationsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/settings': { id: '/admin/settings'; path: '/settings'; fullPath: '/admin/settings'; preLoaderRoute: typeof AdminSettingsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/payouts': { id: '/admin/payouts'; path: '/payouts'; fullPath: '/admin/payouts'; preLoaderRoute: typeof AdminPayoutsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/commissions': { id: '/admin/commissions'; path: '/commissions'; fullPath: '/admin/commissions'; preLoaderRoute: typeof AdminCommissionsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/flash-sales': { id: '/admin/flash-sales'; path: '/flash-sales'; fullPath: '/admin/flash-sales'; preLoaderRoute: typeof AdminFlashSalesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/abandoned-carts': { id: '/admin/abandoned-carts'; path: '/abandoned-carts'; fullPath: '/admin/abandoned-carts'; preLoaderRoute: typeof AdminAbandonedCartsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/wishlist-analytics': { id: '/admin/wishlist-analytics'; path: '/wishlist-analytics'; fullPath: '/admin/wishlist-analytics'; preLoaderRoute: typeof AdminWishlistAnalyticsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/segments': { id: '/admin/segments'; path: '/segments'; fullPath: '/admin/segments'; preLoaderRoute: typeof AdminSegmentsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/loyalty': { id: '/admin/loyalty'; path: '/loyalty'; fullPath: '/admin/loyalty'; preLoaderRoute: typeof AdminLoyaltyRouteImport; parentRoute: typeof AdminRoute }
    '/admin/subscriptions': { id: '/admin/subscriptions'; path: '/subscriptions'; fullPath: '/admin/subscriptions'; preLoaderRoute: typeof AdminSubscriptionsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/gift-cards': { id: '/admin/gift-cards'; path: '/gift-cards'; fullPath: '/admin/gift-cards'; preLoaderRoute: typeof AdminGiftCardsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/sales-analytics': { id: '/admin/sales-analytics'; path: '/sales-analytics'; fullPath: '/admin/sales-analytics'; preLoaderRoute: typeof AdminSalesAnalyticsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/product-performance': { id: '/admin/product-performance'; path: '/product-performance'; fullPath: '/admin/product-performance'; preLoaderRoute: typeof AdminProductPerformanceRouteImport; parentRoute: typeof AdminRoute }
    '/admin/conversion-tracking': { id: '/admin/conversion-tracking'; path: '/conversion-tracking'; fullPath: '/admin/conversion-tracking'; preLoaderRoute: typeof AdminConversionTrackingRouteImport; parentRoute: typeof AdminRoute }
    '/admin/search-analytics': { id: '/admin/search-analytics'; path: '/search-analytics'; fullPath: '/admin/search-analytics'; preLoaderRoute: typeof AdminSearchAnalyticsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/automation-rules': { id: '/admin/automation-rules'; path: '/automation-rules'; fullPath: '/admin/automation-rules'; preLoaderRoute: typeof AdminAutomationRulesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/email-templates': { id: '/admin/email-templates'; path: '/email-templates'; fullPath: '/admin/email-templates'; preLoaderRoute: typeof AdminEmailTemplatesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/sms-templates': { id: '/admin/sms-templates'; path: '/sms-templates'; fullPath: '/admin/sms-templates'; preLoaderRoute: typeof AdminSmsTemplatesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/push-notifications': { id: '/admin/push-notifications'; path: '/push-notifications'; fullPath: '/admin/push-notifications'; preLoaderRoute: typeof AdminPushNotificationsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/api-management': { id: '/admin/api-management'; path: '/api-management'; fullPath: '/admin/api-management'; preLoaderRoute: typeof AdminApiManagementRouteImport; parentRoute: typeof AdminRoute }
    '/admin/webhooks': { id: '/admin/webhooks'; path: '/webhooks'; fullPath: '/admin/webhooks'; preLoaderRoute: typeof AdminWebhooksRouteImport; parentRoute: typeof AdminRoute }
    '/admin/support-tickets': { id: '/admin/support-tickets'; path: '/support-tickets'; fullPath: '/admin/support-tickets'; preLoaderRoute: typeof AdminSupportTicketsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/live-chat': { id: '/admin/live-chat'; path: '/live-chat'; fullPath: '/admin/live-chat'; preLoaderRoute: typeof AdminLiveChatRouteImport; parentRoute: typeof AdminRoute }
    '/admin/feedback': { id: '/admin/feedback'; path: '/feedback'; fullPath: '/admin/feedback'; preLoaderRoute: typeof AdminFeedbackRouteImport; parentRoute: typeof AdminRoute }
    '/admin/disputes': { id: '/admin/disputes'; path: '/disputes'; fullPath: '/admin/disputes'; preLoaderRoute: typeof AdminDisputesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/refunds': { id: '/admin/refunds'; path: '/refunds'; fullPath: '/admin/refunds'; preLoaderRoute: typeof AdminRefundsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/pages': { id: '/admin/pages'; path: '/pages'; fullPath: '/admin/pages'; preLoaderRoute: typeof AdminPagesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/blog': { id: '/admin/blog'; path: '/blog'; fullPath: '/admin/blog'; preLoaderRoute: typeof AdminBlogRouteImport; parentRoute: typeof AdminRoute }
    '/admin/media': { id: '/admin/media'; path: '/media'; fullPath: '/admin/media'; preLoaderRoute: typeof AdminMediaRouteImport; parentRoute: typeof AdminRoute }
    '/admin/seo': { id: '/admin/seo'; path: '/seo'; fullPath: '/admin/seo'; preLoaderRoute: typeof AdminSeoRouteImport; parentRoute: typeof AdminRoute }
    '/admin/roles': { id: '/admin/roles'; path: '/roles'; fullPath: '/admin/roles'; preLoaderRoute: typeof AdminRolesRouteImport; parentRoute: typeof AdminRoute }
    '/admin/login-sessions': { id: '/admin/login-sessions'; path: '/login-sessions'; fullPath: '/admin/login-sessions'; preLoaderRoute: typeof AdminLoginSessionsRouteImport; parentRoute: typeof AdminRoute }
    '/admin/security': { id: '/admin/security'; path: '/security'; fullPath: '/admin/security'; preLoaderRoute: typeof AdminSecurityRouteImport; parentRoute: typeof AdminRoute }
    '/admin/fraud-detection': { id: '/admin/fraud-detection'; path: '/fraud-detection'; fullPath: '/admin/fraud-detection'; preLoaderRoute: typeof AdminFraudDetectionRouteImport; parentRoute: typeof AdminRoute }
    '/admin/backup': { id: '/admin/backup'; path: '/backup'; fullPath: '/admin/backup'; preLoaderRoute: typeof AdminBackupRouteImport; parentRoute: typeof AdminRoute }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/transactions': {
      id: '/account/transactions'
      path: '/transactions'
      fullPath: '/account/transactions'
      preLoaderRoute: typeof AccountTransactionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/refunds': {
      id: '/account/refunds'
      path: '/refunds'
      fullPath: '/account/refunds'
      preLoaderRoute: typeof AccountRefundsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payouts': {
      id: '/account/payouts'
      path: '/payouts'
      fullPath: '/account/payouts'
      preLoaderRoute: typeof AccountPayoutsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/marketing': {
      id: '/account/marketing'
      path: '/marketing'
      fullPath: '/account/marketing'
      preLoaderRoute: typeof AccountMarketingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/delivery': {
      id: '/account/delivery'
      path: '/delivery'
      fullPath: '/account/delivery'
      preLoaderRoute: typeof AccountDeliveryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/refunds/$id': {
      id: '/account/refunds/$id'
      path: '/$id'
      fullPath: '/account/refunds/$id'
      preLoaderRoute: typeof AccountRefundsIdRouteImport
      parentRoute: typeof AccountRefundsRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRefundsRouteChildren {
  AccountRefundsIdRoute: typeof AccountRefundsIdRoute
}

const AccountRefundsRouteChildren: AccountRefundsRouteChildren = {
  AccountRefundsIdRoute: AccountRefundsIdRoute,
}

const AccountRefundsRouteWithChildren = AccountRefundsRoute._addFileChildren(
  AccountRefundsRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountDeliveryRoute: typeof AccountDeliveryRoute
  AccountMarketingRoute: typeof AccountMarketingRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountPayoutsRoute: typeof AccountPayoutsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRefundsRoute: typeof AccountRefundsRouteWithChildren
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountTransactionsRoute: typeof AccountTransactionsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountDeliveryRoute: AccountDeliveryRoute,
  AccountMarketingRoute: AccountMarketingRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountPayoutsRoute: AccountPayoutsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRefundsRoute: AccountRefundsRouteWithChildren,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountTransactionsRoute: AccountTransactionsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminShippingZonesRoute: typeof AdminShippingZonesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminFlashSalesRoute: typeof AdminFlashSalesRoute
  AdminAbandonedCartsRoute: typeof AdminAbandonedCartsRoute
  AdminWishlistAnalyticsRoute: typeof AdminWishlistAnalyticsRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminGiftCardsRoute: typeof AdminGiftCardsRoute
  AdminSalesAnalyticsRoute: typeof AdminSalesAnalyticsRoute
  AdminProductPerformanceRoute: typeof AdminProductPerformanceRoute
  AdminConversionTrackingRoute: typeof AdminConversionTrackingRoute
  AdminSearchAnalyticsRoute: typeof AdminSearchAnalyticsRoute
  AdminAutomationRulesRoute: typeof AdminAutomationRulesRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminSmsTemplatesRoute: typeof AdminSmsTemplatesRoute
  AdminPushNotificationsRoute: typeof AdminPushNotificationsRoute
  AdminApiManagementRoute: typeof AdminApiManagementRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminSupportTicketsRoute: typeof AdminSupportTicketsRoute
  AdminLiveChatRoute: typeof AdminLiveChatRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminLoginSessionsRoute: typeof AdminLoginSessionsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminFraudDetectionRoute: typeof AdminFraudDetectionRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminUsersBannedRoute: typeof AdminUsersBannedRoute
  AdminUsersRolesRoute: typeof AdminUsersRolesRoute
  AdminVendorsPendingRoute: typeof AdminVendorsPendingRoute
  AdminVendorsPerformanceRoute: typeof AdminVendorsPerformanceRoute
  AdminProductsAddRoute: typeof AdminProductsAddRoute
  AdminProductsCategoriesRoute: typeof AdminProductsCategoriesRoute
  AdminProductsSubcategoriesRoute: typeof AdminProductsSubcategoriesRoute
  AdminProductsBrandsRoute: typeof AdminProductsBrandsRoute
  AdminProductsAttributesRoute: typeof AdminProductsAttributesRoute
  AdminProductsInventoryRoute: typeof AdminProductsInventoryRoute
  AdminOrdersPendingRoute: typeof AdminOrdersPendingRoute
  AdminOrdersProcessingRoute: typeof AdminOrdersProcessingRoute
  AdminOrdersShippedRoute: typeof AdminOrdersShippedRoute
  AdminOrdersDeliveredRoute: typeof AdminOrdersDeliveredRoute
  AdminOrdersCancelledRoute: typeof AdminOrdersCancelledRoute
  AdminOrdersReturnsRoute: typeof AdminOrdersReturnsRoute
  AdminShippingChargesRoute: typeof AdminShippingChargesRoute
  AdminShippingCourierRoute: typeof AdminShippingCourierRoute
  AdminMarketingPromotionsRoute: typeof AdminMarketingPromotionsRoute
  AdminReviewsModerationRoute: typeof AdminReviewsModerationRoute
  AdminSupportComplaintsRoute: typeof AdminSupportComplaintsRoute
  AdminSupportHelpCenterRoute: typeof AdminSupportHelpCenterRoute
  AdminSecurityIpRoute: typeof AdminSecurityIpRoute
  AdminSettingsCurrencyRoute: typeof AdminSettingsCurrencyRoute
  AdminSettingsEmailRoute: typeof AdminSettingsEmailRoute
  AdminSettingsOtpRoute: typeof AdminSettingsOtpRoute
  AdminLogsErrorsRoute: typeof AdminLogsErrorsRoute
  AdminBackupRestoreRoute: typeof AdminBackupRestoreRoute
  AdminApiIntegrationsRoute: typeof AdminApiIntegrationsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminShippingZonesRoute: AdminShippingZonesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminFlashSalesRoute: AdminFlashSalesRoute,
  AdminAbandonedCartsRoute: AdminAbandonedCartsRoute,
  AdminWishlistAnalyticsRoute: AdminWishlistAnalyticsRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminGiftCardsRoute: AdminGiftCardsRoute,
  AdminSalesAnalyticsRoute: AdminSalesAnalyticsRoute,
  AdminProductPerformanceRoute: AdminProductPerformanceRoute,
  AdminConversionTrackingRoute: AdminConversionTrackingRoute,
  AdminSearchAnalyticsRoute: AdminSearchAnalyticsRoute,
  AdminAutomationRulesRoute: AdminAutomationRulesRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminSmsTemplatesRoute: AdminSmsTemplatesRoute,
  AdminPushNotificationsRoute: AdminPushNotificationsRoute,
  AdminApiManagementRoute: AdminApiManagementRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminSupportTicketsRoute: AdminSupportTicketsRoute,
  AdminLiveChatRoute: AdminLiveChatRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminLoginSessionsRoute: AdminLoginSessionsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminFraudDetectionRoute: AdminFraudDetectionRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminUsersBannedRoute: AdminUsersBannedRoute,
  AdminUsersRolesRoute: AdminUsersRolesRoute,
  AdminVendorsPendingRoute: AdminVendorsPendingRoute,
  AdminVendorsPerformanceRoute: AdminVendorsPerformanceRoute,
  AdminProductsAddRoute: AdminProductsAddRoute,
  AdminProductsCategoriesRoute: AdminProductsCategoriesRoute,
  AdminProductsSubcategoriesRoute: AdminProductsSubcategoriesRoute,
  AdminProductsBrandsRoute: AdminProductsBrandsRoute,
  AdminProductsAttributesRoute: AdminProductsAttributesRoute,
  AdminProductsInventoryRoute: AdminProductsInventoryRoute,
  AdminOrdersPendingRoute: AdminOrdersPendingRoute,
  AdminOrdersProcessingRoute: AdminOrdersProcessingRoute,
  AdminOrdersShippedRoute: AdminOrdersShippedRoute,
  AdminOrdersDeliveredRoute: AdminOrdersDeliveredRoute,
  AdminOrdersCancelledRoute: AdminOrdersCancelledRoute,
  AdminOrdersReturnsRoute: AdminOrdersReturnsRoute,
  AdminShippingChargesRoute: AdminShippingChargesRoute,
  AdminShippingCourierRoute: AdminShippingCourierRoute,
  AdminMarketingPromotionsRoute: AdminMarketingPromotionsRoute,
  AdminReviewsModerationRoute: AdminReviewsModerationRoute,
  AdminSupportComplaintsRoute: AdminSupportComplaintsRoute,
  AdminSupportHelpCenterRoute: AdminSupportHelpCenterRoute,
  AdminSecurityIpRoute: AdminSecurityIpRoute,
  AdminSettingsCurrencyRoute: AdminSettingsCurrencyRoute,
  AdminSettingsEmailRoute: AdminSettingsEmailRoute,
  AdminSettingsOtpRoute: AdminSettingsOtpRoute,
  AdminLogsErrorsRoute: AdminLogsErrorsRoute,
  AdminBackupRestoreRoute: AdminBackupRestoreRoute,
  AdminApiIntegrationsRoute: AdminApiIntegrationsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SellerRoute: SellerRoute,
  ShopRoute: ShopRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
